CREATE TABLE IF NOT EXISTS ATTENDENCE
(
ATTENDENCE_ID INT,
STUDENT_ID INT ,
SEMESTER INT,
SESSION_NUMBER INT,
SECTION_NUMBER INT,
STATUS VARCHAR(50),
COURSE_CODE INT,
DATE VARCHAR(50),
PRIMARY KEY(ATTENDENCE_ID),
CONSTRAINT FOREIGN_KEY_2 FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
CONSTRAINT FOREIGN_KEY_3 FOREIGN KEY(SECTION_NUMBER) REFERENCES SECTION(SECTION_NUMBER),
CONSTRAINT FOREIGN_KEY_4 FOREIGN KEY(COURSE_CODE) REFERENCES COURSE(COURSE_ID)
);