CREATE TABLE IF NOT EXISTS COURSE
(
COURSE_ID INT NOT NULL,
COURSE_NAME VARCHAR(50) NOT NULL,
PROFESSOR_ID INT NOT NULL,
LTP_STRUCTURE INT ,
PRIMARY KEY(COURSE_ID),
CONSTRAINT FOREIGN_KEY_1 FOREIGN KEY(PROFESSOR_ID) REFERENCES PROFESSOR(PROFESSOR_ID)
);