CREATE TABLE IF NOT EXISTS STUDENT_COURSE
(
SECTION_ID INT,
STUDENT_ID INT,
COURSE_ID INT,
PRIMARY KEY(SECTION_ID),
CONSTRAINT FOREIGN_KEY_18 FOREIGN KEY(STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
CONSTRAINT FOREIGN_KEY_19 FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSE_ID)
);