# Display the ATTENDENCE report consisting of STUDENT_ID, STUDENT_NAME, STATUS, DATE IN SECTION 1?
SELECT S.STUDENT_ID, S.STUDENT_NAME, A.STATUS, A.DATE
FROM ATTENDENCE A INNER JOIN STUDENT S ON A.STUDENT_ID=S.STUDENT_ID
WHERE A.SECTION_NUMBER=1;