# Display the STUDENT names associated with PROFESSOR from SECTION_NUMBER=1?
SELECT A.STUDENT_ID, A.STATUS, A.DATE
FROM ATTENDENCE A INNER JOIN SECTION S ON A.SECTION_NUMBER=S.SECTION_NUMBER
WHERE S.SECTION_SLOT_NUMBER=1;