# How many STUDENTs are being involved in COURSE 150022?
SELECT COUNT(Sc.STUDENT_ID)
FROM STUDENT S, COURSE C, STUDENT_COURSE SC
WHERE S.STUDENT_ID=SC.STUDENT_ID AND C.COURSE_ID=SC.COURSE_ID AND SC.COURSE_ID=150022;