# Display the STUDENT names associated with PROFESSOR from SECTION_NUMBER=1?
SELECT P.PROFESSOR_NAME,ST.STUDENT_NAME
 FROM SECTION S INNER JOIN PROFESSOR P ON P.SECTION_NUMBER=S.SECTION_NUMBER INNER JOIN STUDENT ST ON ST.SECTION_NUMBER = S.SECTION_NUMBER
 WHERE S.SECTION_NUMBER=1;